In [65]:
import numpy as np
cool_list = [20,27,9,12,31,17,4,50,39,35]
arr = np.array(cool_list)
print(4*arr)
print(np.mean(cool_list))
print(np.median(cool_list))
print(np.std(cool_list))
min_index = np.argmin(cool_list)
print(cool_list[min_index])
max_index = np.argmax(cool_list)
print(cool_list[max_index])
print(np.min(cool_list))
print(np.max(cool_list))
boolean_arr = arr[arr >20]
print(boolean_arr)

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
4
50
4
50
[27 31 50 39 35]


In [32]:
matrix = [
    [5, 12, 17, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
]
arr = np.array(matrix)
print(arr.shape) #prints rows, columns. in this case it will print (3,4)
print(arr[:,2])
print(arr[1])
print(2*arr)
for i in range(4):
    print(np.mean(arr[:,i]))
print(np.mean(arr))
for i in range(4):
    print(np.max(arr[:,i]))
    print(np.min(arr[:,i]))
print(arr.flatten()) #turns into one long list
print(np.argmin(arr))
print(np.argmax(arr))
np.unravel_index(2,arr.shape)
boolean_arr = arr[arr > 15]
sorted_array = np.array([])
for i in range(3):
    row = np.sort(arr[i])
    sorted_array =+ np.append(sorted_array,row)
    print(sorted_array)

(3, 4)
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
6.333333333333333
15.333333333333334
16.666666666666668
7.666666666666667
11.5
8
5
21
12
19
14
11
3
[ 5 12 17  9  8 21 14  3  6 13 19 11]
7
5
[ 5.  9. 12. 17.]
[ 5.  9. 12. 17.  3.  8. 14. 21.]
[ 5.  9. 12. 17.  3.  8. 14. 21.  6. 11. 13. 19.]


In [37]:
arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])
def is_prime(n):
    if n<2:
        return False 
    for i in range(2,n):
        if n % i == 0:
            return False 
    return True 
def alien_star(array): 
    result = []
    for row in array:
        for num in row: 
                if is_prime(num):
                    result.append(row)
                    break
        return np.array(result)
    
print(alien_star(arr))


[[2 3 5]]


In [54]:
arr2 = np.zeros((8,8))
for i in range(arr2.shape[0]):
    for j in range(arr2.shape[1]):
        if (i + j) %2 == 0:
            arr2[i,j] = 1
print(arr2)
def reverse_checkerboard(board):
    for j in range(board.shape[0]):
        for i in range(board.shape[1]):
            if (i + j) % 2 == 0:
                board[i,j] = 0
            else:
                board[i,j] = 1
    return board
                
print(reverse_checkerboard(arr2))


[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [76]:
def expand_universe(input_str, num):
    string_array = list(input_str)
    spaced_array = []
    for i in range(len(string_array)): 
        spaced_array.append(string_array[i])
        if i != len(string_array)-1:
            for j in range(num): 
                spaced_array.append(" ")
    return ''.join(spaced_array)
expand_universe("test", 2)

't  e  s  t'

In [83]:
star_array = ([[1123, 1456, 1789, 1324, 1876],
[1567, 1987, 1678, 1405, 1589],
[1345, 1654, 1523, 1109, 1923],
[1298, 1890, 1367, 1784, 1432],
[1823, 1756, 1489, 1672, 1550]])
def find_guide_star(array):
    result = []
    for row in array:
        sorted_row = np.sort(row)
        result.append(sorted_row[-2])
    return np.array(result)
print(find_guide_star(star_array))

[1789 1678 1654 1784 1756]
